sudo: false

notifications:
  email: false

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - python suiltes/manage.py test app
  - coverage suiltes/run manage.py test app

after_success:
  - codecov
