sudo: false

notifications:
  email: false

language: python

services:
  - mysql

python:
  - 3.4

install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database suites;'
  - python ./suiltes/manage.py migrate
  # - python ./suiltes/manage.py syncdb --noinput
script: ./suiltes/manage.py test app
