sudo: false

notifications:
  email: false

language: python

services:
  - mysql

python:
  - 3.4

install:
  - pip install Django==1.9
  - pip install django-bootstrap3

before_script:
  - python manage.py migrate

script:
  - ./suiltes/manage.py test
