sudo: false

notifications:
  email: false

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - python suiltes/manage.py test app
  - coverage run manage.py test

after_success:
  codecov
