sudo: false

notifications:
  email: false

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python suiltes/manage.py test app

after_success:
  coveralls
