sudo: false

notifications:
  email: false

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt

#before_script:
#  - python suiltes/manage.py makemigrations
#  - python suiltes/manage.py migrate

script:
  - python suiltes/manage.py test
