sudo: false

notifications:
  email: false

language: python

branches:
  only:
    - master

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

before_script:
  - cd suiltes

script:
  - python manage.py test app
  - coverage run manage.py test app

after_success:
  - codecov
