sudo: false

notifications:
  email: false

language: python

services:
  - mysql

python:
  - 3.4

install:
  - pip install Django==1.9
  - pip install django-bootstrap3

script: ./suiltes/manage.py test
