# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('run', models.CharField(max_length=40)),
            ],
        ),
    ]
