# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
